# Generated by Django 5.1.6 on 2025-03-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('carType', models.CharField(max_length=50)),
                ('plateNumber', models.CharField(max_length=50)),
                ('stateCovered', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('categoryID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('itemType', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=200)),
                ('pointsGiven', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operatorID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucherID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('pointsRequired', models.IntegerField()),
                ('termsCondition', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('requestID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.itemcategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.driver')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.operator')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRedemption',
            fields=[
                ('redemptionID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.voucher')),
            ],
        ),
    ]
