# Generated by Django 5.1.7 on 2025-03-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
