# Generated by Django 5.1.6 on 2025-03-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickeduprequest',
            name='requestID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickedup_requests', to='database.schedulerequest'),
        ),
    ]
