# Generated by Django 5.1.7 on 2025-03-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_customer_age_alter_customer_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='rejectedReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.driver'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.operator'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='weight',
            field=models.TextField(),
        ),
    ]
