# Generated by Django 5.1.6 on 2025-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_pickuprequest_trackingnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='carType',
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='trackingnumber',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
