# Generated by Django 5.1.6 on 2025-03-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_driver_cartype_alter_driver_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='termsCondition',
        ),
    ]
