# Generated by Django 5.1.6 on 2025-03-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_voucher_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerredemption',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerredemption',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
