# Generated by Django 5.1.6 on 2025-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_customerredemption_date_customerredemption_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='example',
        ),
    ]
