# Generated by Django 5.1.6 on 2025-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_itemcategory_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phoneNumber',
            field=models.IntegerField(default=123),
        ),
    ]
