# Generated by Django 5.1.6 on 2025-04-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_completedrequest_requestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='completedrequest',
            name='requestID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_requests', to='database.schedulerequest'),
        ),
    ]
