# Generated by Django 5.1.6 on 2025-04-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_customer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
