# Generated by Django 5.1.7 on 2025-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_driver_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postalCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='areaCovered',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='postalCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
